---
title: "Dashboard"
author: "Zongchao Liu"
date: "10/27/2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```


```{r}
data("ny_noaa")

processed_data <-
  ny_noaa %>%
  mutate(date_preserved = date) %>%
  separate(date, into = c("year", "month", "day")) %>%
  mutate( year = as.numeric(year))
```


Column {data-width=650}
-----------------------------------------------------------------------

### The Trend of the Temperature in WATERTOWN AIRPORT, 2000

```{r}
processed_data %>%
  drop_na(snwd) %>%
  mutate(tmin = as.numeric(tmin),
         tmax = as.numeric(tmax)) %>%
  filter(id == "USW00094790",
         year == 2000) %>%
  plot_ly(y = ~ date_preserved, x = ~ (tmin/10), z = ~ (tmax/10)) %>%
  add_trace(opacity = 0.3) %>% 
  layout(title = "The Trend of the Temperature in WATERTOWN AIRPORT, 2000",
         xaxis = list(title = "Tmin"),
         yaxis = list(title = "Tmax"),
         zaxis = list(title = "Date"))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Monthly Changes of Average Max-temperature in Watertown Airport, 1985 ~ 2005

```{r}
# monthly average max-temperature
processed_data %>%
  mutate(tmax = as.numeric(tmax),
         tmax_c = tmax/10) %>%
  filter(id == "USW00094790") %>%
  filter(year >= 1984 & year <= 2007) %>%
  group_by(year,month) %>%
  summarise(tmax_month_year = mean(tmax)/10) %>%
  plot_ly( x = ~ month, y = ~ year, z = ~ tmax_month_year , type = "heatmapgl",
           colors = colorRamp(c("white", "orange","red"))) %>%
  layout(title = "Monthly Changes of Average Max-temperature in Watertown Airport, 1985 ~ 2005", font = list(size = 8)) %>% 
  layout(xaxis = list(title = "Month"),
         yaxis = list(title = "Year"))

```


### Monthly Changes of Precipitation in Watertown Airport, 1985 ~ 2010

```{r}
ny_noaa %>%
  mutate(date_preserved = date) %>%
  separate(date, into = c("year", "month", "day")) %>%
  mutate( year = as.numeric(year)) %>%
  filter(id == "USW00094790" & year >= 1984 ) %>%
  mutate(year = as.character(year)) %>%
  plot_ly( x = ~ date_preserved, y = ~ prcp,  type = "bar", color = ~year) %>%
  layout( title = "Monthly Changes of Precipitation in Watertown Airport, 1985 ~ 2010", font = list(size =8)) %>%
  layout(xaxis = list(title = "Date"),
         yaxis = list(title = "Precipitation"))
  
```